//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AugustUIChallenge.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AugustUIChallenge.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string FindYourDoctorLabel {
            get {
                return ResourceManager.GetString("FindYourDoctorLabel", resourceCulture);
            }
        }
        
        internal static string SearchDoctorLabel {
            get {
                return ResourceManager.GetString("SearchDoctorLabel", resourceCulture);
            }
        }
        
        internal static string ExperienceLabel {
            get {
                return ResourceManager.GetString("ExperienceLabel", resourceCulture);
            }
        }
        
        internal static string PatientsLabel {
            get {
                return ResourceManager.GetString("PatientsLabel", resourceCulture);
            }
        }
        
        internal static string GreetingLabel {
            get {
                return ResourceManager.GetString("GreetingLabel", resourceCulture);
            }
        }
        
        internal static string NearbyDoctorsLabel {
            get {
                return ResourceManager.GetString("NearbyDoctorsLabel", resourceCulture);
            }
        }
        
        internal static string DoctorProfileTitle {
            get {
                return ResourceManager.GetString("DoctorProfileTitle", resourceCulture);
            }
        }
        
        internal static string BookLabel {
            get {
                return ResourceManager.GetString("BookLabel", resourceCulture);
            }
        }
        
        internal static string DoctorReviewsLabel {
            get {
                return ResourceManager.GetString("DoctorReviewsLabel", resourceCulture);
            }
        }
        
        internal static string PositiveReviewsLabel {
            get {
                return ResourceManager.GetString("PositiveReviewsLabel", resourceCulture);
            }
        }
        
        internal static string MakeBookingButton {
            get {
                return ResourceManager.GetString("MakeBookingButton", resourceCulture);
            }
        }
        
        internal static string FindDoctorButton {
            get {
                return ResourceManager.GetString("FindDoctorButton", resourceCulture);
            }
        }
        
        internal static string SpecialityLabel {
            get {
                return ResourceManager.GetString("SpecialityLabel", resourceCulture);
            }
        }
        
        internal static string LocationLabel {
            get {
                return ResourceManager.GetString("LocationLabel", resourceCulture);
            }
        }
        
        internal static string AvailabilityLabel {
            get {
                return ResourceManager.GetString("AvailabilityLabel", resourceCulture);
            }
        }
        
        internal static string SpecialityPlaceholder {
            get {
                return ResourceManager.GetString("SpecialityPlaceholder", resourceCulture);
            }
        }
        
        internal static string LocationPlaceholder {
            get {
                return ResourceManager.GetString("LocationPlaceholder", resourceCulture);
            }
        }
    }
}
